"""
Database module for the Healthcare Flask application.
Supports both SQLite (local development) and PostgreSQL (production).
"""
import logging
import os
import sqlite3
import secrets
from contextlib import contextmanager
from werkzeug.security import generate_password_hash, check_password_hash
from urllib.parse import urlparse

logger = logging.getLogger(__name__)

# Database configuration
DATABASE_URL = os.environ.get('DATABASE_URL', 'sqlite:///healthcare.db')

# User-facing messages. Raw exception text is never returned to the UI.
ACCOUNT_CREATE_FAILED = 'We could not create your account right now. Please try again later.'
APPOINTMENT_CREATE_FAILED = 'We could not book your appointment right now. Please try again later.'

# Parse database URL to determine driver and connection params
def _parse_database_url(url):
    """Parse database URL and return connection parameters."""
    parsed = urlparse(url)
    return {
        'driver': parsed.scheme,
        'host': parsed.hostname,
        'port': parsed.port,
        'database': parsed.path.lstrip('/'),
        'username': parsed.username,
        'password': parsed.password,
    }

DB_CONFIG = _parse_database_url(DATABASE_URL)

@contextmanager
def get_db_connection():
    """Get a database connection with row factory.
    
    Supports both SQLite (local) and PostgreSQL (production).
    """
    driver = DB_CONFIG['driver']
    
    if driver == 'sqlite':
        # SQLite connection
        db_path = DB_CONFIG['database']
        if db_path.startswith('/'):
            # Absolute path
            path = db_path
        else:
            # Relative path - make it relative to this file
            path = os.path.join(os.path.dirname(__file__), db_path)
        conn = sqlite3.connect(path)
        conn.row_factory = sqlite3.Row
        try:
            yield conn
        finally:
            conn.close()
    elif driver in ('postgres', 'postgresql'):
        # PostgreSQL connection
        import psycopg2
        from psycopg2.extras import RealDictCursor
        conn = psycopg2.connect(
            host=DB_CONFIG['host'],
            port=DB_CONFIG['port'] or 5432,
            database=DB_CONFIG['database'],
            user=DB_CONFIG['username'],
            password=DB_CONFIG['password'],
            cursor_factory=RealDictCursor
        )
        conn.autocommit = False
        try:
            yield conn
        finally:
            conn.close()
    else:
        raise ValueError(f"Unsupported database driver: {driver}")

def _get_placeholder():
    """Return the appropriate placeholder for the current database driver."""
    return '?' if DB_CONFIG['driver'] == 'sqlite' else '%s'

def _get_autoincrement():
    """Return the appropriate autoincrement syntax for the current database driver."""
    if DB_CONFIG['driver'] == 'sqlite':
        return 'AUTOINCREMENT'
    else:
        # PostgreSQL: use modern IDENTITY syntax (standard SQL, supported in PG 10+)
        return 'GENERATED BY DEFAULT AS IDENTITY'

def _get_timestamp_default():
    """Return the appropriate timestamp default for the current database driver."""
    if DB_CONFIG['driver'] == 'sqlite':
        return 'DEFAULT CURRENT_TIMESTAMP'
    else:
        return 'DEFAULT NOW()'

def init_db():
    """Initialize the database with required tables."""
    with get_db_connection() as conn:
        cursor = conn.cursor()
        placeholder = _get_placeholder()
        autoinc = _get_autoincrement()
        ts_default = _get_timestamp_default()
        
        # Users table
        # NOTE: email and password_hash are legacy columns that already exist in the
        # production database with NOT NULL/UNIQUE constraints. They are kept for
        # schema compatibility but are never used for authentication - the app
        # authenticates with Patient ID + Secret Code only.
        cursor.execute(f'''
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY {autoinc},
                full_name TEXT NOT NULL,
                email TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                created_at TIMESTAMP {ts_default},
                patient_id TEXT UNIQUE,
                secret_code_hash TEXT
            )
        ''')
        
        # Add patient ID and secret code hash columns if they don't exist (migration for existing databases)
        _add_patient_auth_columns_if_missing(cursor)
        
        # Appointments table
        cursor.execute(f'''
            CREATE TABLE IF NOT EXISTS appointments (
                id INTEGER PRIMARY KEY {autoinc},
                user_id INTEGER NOT NULL,
                doctor_id INTEGER NOT NULL,
                appointment_date TEXT NOT NULL,
                appointment_time TEXT NOT NULL,
                notes TEXT,
                created_at TIMESTAMP {ts_default},
                FOREIGN KEY (user_id) REFERENCES users (id)
            )
        ''')
        
        conn.commit()


def _add_patient_auth_columns_if_missing(cursor):
    """Add patient ID and secret code hash columns to users table if they don't exist."""
    if DB_CONFIG['driver'] == 'sqlite':
        cursor.execute("PRAGMA table_info(users)")
        columns = [col[1] for col in cursor.fetchall()]
    else:
        cursor.execute("SELECT column_name FROM information_schema.columns WHERE table_name = 'users'")
        columns = [col['column_name'] for col in cursor.fetchall()]
    
    if 'patient_id' not in columns:
        cursor.execute('ALTER TABLE users ADD COLUMN patient_id TEXT')
        # Create unique index for patient_id
        if DB_CONFIG['driver'] == 'sqlite':
            cursor.execute('CREATE UNIQUE INDEX IF NOT EXISTS idx_users_patient_id ON users(patient_id)')
        else:
            cursor.execute('CREATE UNIQUE INDEX IF NOT EXISTS idx_users_patient_id ON users(patient_id)')
    if 'secret_code_hash' not in columns:
        cursor.execute('ALTER TABLE users ADD COLUMN secret_code_hash TEXT')


def generate_patient_id():
    """Generate a unique patient ID in format HC-YYYY-NNNNN."""
    from datetime import datetime
    year = datetime.now().year
    placeholder = _get_placeholder()
    with get_db_connection() as conn:
        cursor = conn.cursor()
        # Get max sequence number for this year to generate next sequential number
        # Format: HC-YYYY-NNNNN, sequence starts at position 9 (1-indexed)
        if DB_CONFIG['driver'] == 'sqlite':
            cursor.execute(f'''
                SELECT MAX(CAST(SUBSTR(patient_id, 9) AS INTEGER)) as max_seq 
                FROM users 
                WHERE patient_id LIKE {placeholder}
            ''', (f'HC-{year}-%',))
        else:
            cursor.execute(f'''
                SELECT MAX(CAST(SUBSTR(patient_id, 9) AS INTEGER)) as max_seq 
                FROM users 
                WHERE patient_id LIKE {placeholder}
            ''', (f'HC-{year}-%',))
        row = cursor.fetchone()
        max_seq = row['max_seq'] if row and row['max_seq'] is not None else 0
        # Next sequence number
        sequence = max_seq + 1
        return f'HC-{year}-{sequence:05d}'


def generate_secret_code():
    """Generate a strong random secret code for patient authentication."""
    # Use secrets module for cryptographically secure random generation
    # Format: 4 groups of 4 alphanumeric characters = 16 chars total
    alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    groups = []
    for _ in range(4):
        group = ''.join(secrets.choice(alphabet) for _ in range(4))
        groups.append(group)
    return '-'.join(groups)


def _is_patient_id_collision(exc):
    """Return True when a unique violation was caused by the patient_id column."""
    text = str(exc).lower()
    return ('unique' in text or 'duplicate' in text) and 'patient_id' in text


def create_user(full_name, patient_id=None, secret_code_hash=None):
    """
    Create a new patient account.

    Authentication is Patient ID + Secret Code only: no email address and no
    password are collected. The legacy email/password_hash columns are NOT NULL
    (and email is UNIQUE) in the existing schema, so non-routable placeholder
    values are stored for them. Those values are never used for authentication
    and no email is ever sent.

    If patient_id and secret_code_hash are not provided, they are generated.

    Returns:
        tuple: (success, message, user_id or None, patient_id, secret_code)
    """
    # Generate the secret code once so every retry stores the same hash.
    if secret_code_hash is None:
        secret_code = generate_secret_code()
        secret_code_hash = generate_password_hash(secret_code)
    else:
        secret_code = None  # We don't have the plaintext if the hash was provided

    # Random value that satisfies the legacy NOT NULL password_hash constraint.
    # No password authentication exists, so nothing can ever match it.
    legacy_password_hash = generate_password_hash(secrets.token_urlsafe(32))

    placeholder = _get_placeholder()
    insert_sql = (
        'INSERT INTO users (full_name, email, password_hash, patient_id, secret_code_hash) '
        f'VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})'
    )

    for attempt in range(3):
        try:
            if patient_id is None:
                patient_id = generate_patient_id()

            params = (
                full_name,
                f'{patient_id.lower()}@noemail.invalid',
                legacy_password_hash,
                patient_id,
                secret_code_hash,
            )

            with get_db_connection() as conn:
                cursor = conn.cursor()
                if DB_CONFIG['driver'] == 'sqlite':
                    cursor.execute(insert_sql, params)
                    conn.commit()
                    user_id = cursor.lastrowid
                else:
                    # psycopg2 uses RealDictCursor, so fetchone() returns a dict
                    # and must be indexed by column name, never by position.
                    cursor.execute(insert_sql + ' RETURNING id', params)
                    user_id = cursor.fetchone()['id']
                    conn.commit()

            return True, 'Account created successfully', user_id, patient_id, secret_code
        except Exception as exc:
            logger.exception('Failed to create user account')
            if _is_patient_id_collision(exc) and attempt < 2:
                # Very unlikely patient ID collision - generate a new one and retry.
                patient_id = None
                continue
            return False, ACCOUNT_CREATE_FAILED, None, None, None

    return False, ACCOUNT_CREATE_FAILED, None, None, None


def get_user_by_id(user_id):
    """Get user by ID."""
    placeholder = _get_placeholder()
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(f'SELECT id, full_name, patient_id, created_at FROM users WHERE id = {placeholder}', (user_id,))
        return cursor.fetchone()


def create_appointment(user_id, doctor_id, appointment_date, appointment_time, notes):
    """
    Create a new appointment for a user.
    
    Returns:
        tuple: (success, message, appointment_id or None)
    """
    placeholder = _get_placeholder()
    insert_sql = (
        'INSERT INTO appointments '
        '(user_id, doctor_id, appointment_date, appointment_time, notes) '
        f'VALUES ({placeholder}, {placeholder}, {placeholder}, {placeholder}, {placeholder})'
    )
    params = (user_id, doctor_id, appointment_date, appointment_time, notes)

    try:
        with get_db_connection() as conn:
            cursor = conn.cursor()
            if DB_CONFIG['driver'] == 'sqlite':
                cursor.execute(insert_sql, params)
                conn.commit()
                appointment_id = cursor.lastrowid
            else:
                # psycopg2 uses RealDictCursor: fetchone() returns a dict, so it
                # must be indexed by column name, never by position.
                cursor.execute(insert_sql + ' RETURNING id', params)
                appointment_id = cursor.fetchone()['id']
                conn.commit()
        return True, 'Appointment booked successfully', appointment_id
    except Exception:
        logger.exception('Failed to create appointment')
        return False, APPOINTMENT_CREATE_FAILED, None


def get_user_appointments(user_id):
    """Get all appointments for a user."""
    placeholder = _get_placeholder()
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(f'''
            SELECT a.*, d.name as doctor_name, d.specialization
            FROM appointments a
            LEFT JOIN (
                SELECT 1 as id, 'Dr. Sarah Johnson' as name, 'Cardiology' as specialization UNION
                SELECT 2, 'Dr. Michael Chen', 'Endocrinology' UNION
                SELECT 3, 'Dr. Emily Rodriguez', 'Family Medicine' UNION
                SELECT 4, 'Dr. James Wilson', 'Pulmonology' UNION
                SELECT 5, 'Dr. Lisa Thompson', 'Dermatology' UNION
                SELECT 6, 'Dr. Robert Kim', 'Orthopedics'
            ) d ON a.doctor_id = d.id
            WHERE a.user_id = {placeholder}
            ORDER BY a.appointment_date, a.appointment_time
        ''', (user_id,))
        return cursor.fetchall()


def get_appointment_by_id(appointment_id, user_id):
    """Get a specific appointment for a user."""
    placeholder = _get_placeholder()
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(f'''
            SELECT a.*, d.name as doctor_name, d.specialization
            FROM appointments a
            LEFT JOIN (
                SELECT 1 as id, 'Dr. Sarah Johnson' as name, 'Cardiology' as specialization UNION
                SELECT 2, 'Dr. Michael Chen', 'Endocrinology' UNION
                SELECT 3, 'Dr. Emily Rodriguez', 'Family Medicine' UNION
                SELECT 4, 'Dr. James Wilson', 'Pulmonology' UNION
                SELECT 5, 'Dr. Lisa Thompson', 'Dermatology' UNION
                SELECT 6, 'Dr. Robert Kim', 'Orthopedics'
            ) d ON a.doctor_id = d.id
            WHERE a.id = {placeholder} AND a.user_id = {placeholder}
        ''', (appointment_id, user_id))
        return cursor.fetchone()


def get_user_by_patient_id(patient_id):
    """Get user by patient ID."""
    placeholder = _get_placeholder()
    with get_db_connection() as conn:
        cursor = conn.cursor()
        cursor.execute(f'SELECT * FROM users WHERE patient_id = {placeholder}', (patient_id,))
        return cursor.fetchone()


def verify_secret_code(patient_id, secret_code):
    """
    Verify a patient's secret code against its stored hash.
    
    Returns:
        tuple: (success, user_data or None)
    """
    user = get_user_by_patient_id(patient_id)
    if not user or not user['secret_code_hash']:
        return False, None
    
    if check_password_hash(user['secret_code_hash'], secret_code):
        return True, user
    return False, None


# Initialize database on import
init_db()